application: sodium-burner-91110
version: 1
runtime: python27
api_version: 1
threadsafe: false


handlers:
#- url: /_ah/queue/deferred
#  script: djangoappengine.deferred.handler.application
#  login: admin
# This handler routes requests for application statistics.
# See https://developers.google.com/appengine/docs/python/tools/appstats
#- url: /_ah/stats/.*
#  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /static/admin/
  static_dir: admin/
  expiration: '0'

- url: /static/
  static_dir: online_forms/static/
  expiration: '0'

- url: /static/online_forms/
  static_dir: online_forms/static/

# This handler catches all requests that don't match a previous handler.

- url: .*
  script: main.py

libraries:
- name: django
  version: 1.5
- name: MySQLdb
  version: "latest"

builtins:
- django_wsgi: on

